/*
  |---------------------------------------------------------|
  |---                                                    --|
  |--                    DO NOT MODIFY                    --|
  |--        Autogenerated file: built by build.sh        --|
  |---                                                    --|
  |---------------------------------------------------------|
*/
import entityPost from './routes/entity/post/handler';

const defineRoutes = (app: import('express').Application) => {
  // POST /entity
  app.post('/entity', entityPost);

};

export default defineRoutes;
